/*
﻿Developed with the contribution of the European Commission - Directorate General for Maritime Affairs and Fisheries
© European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can
redistribute it and/or modify it under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version. The IFDM Suite is distributed in
the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.
 */
package eu.europa.ec.fisheries.uvms.plugins.flux.movement.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import un.unece.uncefact.data.standard.fluxvesselpositionmessage._4.FLUXVesselPositionMessage;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-01-29T13:39:17.214+01:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:xeu:bridge-connector:wsdl:v1", name = "BridgeConnectorPortType")
//@XmlSeeAlso({ObjectFactoryForTypedPayload.class})
@XmlSeeAlso({FLUXVesselPositionMessage.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BridgeConnectorPortTypeForTypedPayload {

    @WebResult(name = "Connector2BridgeResponse", targetNamespace = "urn:xeu:bridge-connector:v1", partName = "output")
    @WebMethod(action = "urn:xeu:bridge-connector:wsdl:v1:post")
    public xeu.bridge_connector.v1.ResponseType post(
        @WebParam(partName = "parameter", name = "Connector2BridgeRequest", targetNamespace = "urn:xeu:bridge-connector:v1")
        RequestTypeWithTypedPayload parameter
    );
}
